export const DEFAULT_AGENT_EMAILS = [
  'vandana.s@nobroker.in',
  'gajula.srikanth@nobroker.in',
  'idanakanti.jeevitha@nobroker.in',
  'maheen.azim@nobroker.in',
  'suman.6@nobroker.in',
  'shapeena.6@nobroker.in',
  'devarapalli.vamsi@nobroker.in',
  'anjali.ashok@nobroker.in',
  'rakshit.bhandari@nobroker.in',
  'manik.dutta@nobroker.in',
  'manojkumar.m@nobroker.in',
  'tejaswini.1@nobroker.in',
  'sai.jyothi@nobroker.in',
  'sreemanth.reddy@nobroker.in',
  's.madhusudhan@nobroker.in',
  'dharsun.ravichandran@nobroker.in',
  'yelisa.sai@nobroker.in',
  'ananya.v@nobroker.in',
  'ananya.mahesh@nobroker.in',
  'swathi.chellamuthu@nobroker.in',
  'aarthi.g@nobroker.in',
  'shyam.sahu@nobroker.in',
  'pondara.ambika@nobroker.in',
  'shankar.prasad@nobroker.in',
  'buddaiah.doddi@nobroker.in',
  'parthasarathy.rs@nobroker.in',
  'kankan.kander@nobroker.in',
  'oshin.thomas@nobroker.in',
  'sujal.sahu@nobroker.in',
  'shivam.vaish@nobroker.in',
  'pinky.rawat@nobroker.in',
  'nandhini.m@nobroker.in',
  'danish.nazir@nobroker.in',
  'biswajit.ghosh2@nobroker.in',
  'lohitha.kanasani@nobroker.in',
  'falak.gaffar@nobroker.in',
  'zubaida.y@nobroker.in',
  'k.bhavani@nobroker.in',
  'shalini.muthusamy@nobroker.in',
  'manoj.c@nobroker.in',
  'yogesh.kumar1@nobroker.in',
  'naveenkumar.balasubramani@nobroker.in',
  'durga.prasad1@nobroker.in',
  'charan.c@nobroker.in',
  'vikas.gurjar@nobroker.in',
  'riya.khan@nobroker.in',
  'surya.m2@nobroker.in'
].sort();

export const DEFAULT_AUDITOR_EMAILS = [
    'moulik.jain@nobroker.in',
    'sradha.suman@nobroker.in',
    'lavkesh.barua@nobroker.in',
    'manojkumar.m@nobroker.in',
    's.madhusudhan@nobroker.in',
    'ujjwal.shahi@nobroker.in'
].sort();


export const LOW_SCORE_THRESHOLD = 4;